name: CI for Preview Branches
on:
  push:
    branches-ignore: ['main', 'staging']
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  checks:
    needs: [ci]
    steps:
      name: Done
      run: echo "Done"
